import {  Poppins } from "next/font/google";
import "./globals.css";


export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose weights you need
  variable: "--font-poppins",          // custom CSS variable
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${poppins.className} antialiased font-poppins max-w-[1920px] mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
